# Generated by Django 3.0.2 on 2020-01-02 12:43

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='qrcode',
            field=models.FileField(default='/data/', upload_to=cases.models.qrcode_directory_path),
            preserve_default=False,
        ),
    ]
