# Generated by Django 3.0.2 on 2020-01-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
    ]
