# Generated by Django 3.0.2 on 2020-01-07 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='loc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='meta',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
