# Generated by Django 3.0.2 on 2020-01-07 07:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200107_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
