# Generated by Django 3.0.2 on 2020-01-08 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='case occured'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='rec_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date recorded'),
            preserve_default=False,
        ),
    ]
