# Generated by Django 3.0.2 on 2020-01-09 06:49

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_video_is_preprocessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to=cases.models.image_directory_path)),
                ('improvement', models.ImageField(blank=True, null=True, upload_to=cases.models.image_directory_path)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.Video')),
            ],
        ),
    ]
