# Generated by Django 3.0.2 on 2020-01-11 10:41

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=cases.models.video_directory_path),
            preserve_default=False,
        ),
    ]
