# Generated by Django 3.0.2 on 2020-01-11 11:11

import app.storage
import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(storage=app.storage.OverwriteStorage(), upload_to=cases.models.video_directory_path),
        ),
    ]
