# Generated by Django 3.0.2 on 2020-01-13 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200111_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rec_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
