# Generated by Django 3.0.2 on 2020-01-21 04:16

import app.storage
import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20200113_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='improvement',
            field=models.ImageField(blank=True, null=True, storage=app.storage.OverwriteStorage(), upload_to=cases.models.image_directory_path),
        ),
    ]
