# Generated by Django 3.0.2 on 2020-01-28 07:55

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20200121_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='query_feature',
            field=models.FileField(default='', upload_to=cases.models.image_directory_path),
            preserve_default=False,
        ),
    ]
