# Generated by Django 3.0.2 on 2020-01-30 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_image_query_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rec_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
