# Generated by Django 3.1 on 2020-08-28 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_case_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
