# Generated by Django 3.1 on 2020-08-28 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_video_original_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='rec_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
