# Generated by Django 3.1 on 2020-08-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20200828_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hash',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
