# Generated by Django 3.1.4 on 2021-04-21 13:39

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_video_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload2',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.video_directory_path),
        ),
    ]
